export const ADD_FAVOR_VIDEO = 'ADD_FAVOR_VIDEO';
export const REPLACE_FAVOR_VIDEO = 'REPLACE_FAVOR_VIDEO';
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
export const SELECT_ROW = 'SELECT_ROW';
export const CHANGE_FONTSIZE = 'CHANGE_FONTSIZE';
export const FONTSIZE_DEC = 'FONTSIZE_DEC';
